/*
===============================================================
📘 README - ESP32 LED Slave Controller with WebSocket + RS485
===============================================================

🛠️ PROJECT OVERVIEW:
---------------------
This code runs on an ESP32-based LED controller acting as a *slave node*
in a distributed LED system. It listens for commands over both:
  ➤ WebSocket (Wi-Fi)
  ➤ RS485 Serial (UART2)

Each "slave" board drives a single LED strip and changes color on command.

📦 FEATURES:
-------------
✔ 900 individually addressable LEDs via Adafruit NeoPixel library  
✔ OTA Firmware Update via Web Interface  
✔ RS485 Serial Control (text + 6-byte binary command)  
✔ Web Console with command input and real-time logs  
✔ Persistent Slave ID using Preferences (NVS)

📐 HARDWARE CONNECTIONS:
--------------------------
- LED Strip Data    ➤ GPIO 5
- RS485 RX (RO)     ➤ GPIO 16
- RS485 TX (DI)     ➤ GPIO 17
- RS485 DE+RE (DIR) ➤ GPIO 4 (controls transmit mode)

💡 LED STRIP DETAILS:
----------------------
- Type: WS2812 (or compatible)
- Number of LEDs: 900
- Controlled via: `Adafruit_NeoPixel`

📡 NETWORK:
------------
- SSID: Gokapture
- Password: P@ssw0rd
- Hostname: `slave<ID>.local` (e.g., slave1.local)
- WebSocket Path: `/ws`
- OTA Update Path: `/update`
- Web Console: accessible at root `/`

💬 COMMAND FORMAT:
-------------------
➤ Text Command via WebSocket or RS485 (ending with newline):

    "<slave_id> <color>"

    Examples:
      - "0 red"
      - "1 off"
      - "2 green"

    Colors supported: red, green, blue, yellow, white, off

➤ Binary Command via RS485 (6 bytes):
    [slave_id, box_index, reserved, R, G, B]

    - Triggers lighting a specific box (group of LEDs)
    - Each "box" = 25 LEDs

🌐 WEB INTERFACE:
------------------
Access the console via IP or mDNS:
  - Example: `http://slave1.local`
  - Features:
    - Send test commands
    - Monitor live logs
    - Upload firmware via OTA update

🔁 FIRMWARE UPDATE (OTA):
--------------------------
1. Visit `/update` from a browser.
2. Upload `.bin` file generated by PlatformIO or Arduino IDE.
3. Device will reboot with the new firmware.

🧠 SLAVE ID CONFIGURATION:
----------------------------
Slave ID is stored in NVS Preferences under key `"id"`:
  - Namespace: `"slave"`
  - Key: `"id"`
To change slave ID:
  - Use a separate setup sketch or expose a Web UI feature to modify it.

🔧 LIBRARIES REQUIRED:
------------------------
- WiFi.h
- AsyncTCP.h
- ESPAsyncWebServer.h
- Preferences.h
- ESPmDNS.h
- Update.h
- Adafruit_NeoPixel.h

📌 NOTES:
-----------
- `RS485Serial` uses UART2.
- The RS485 direction pin is actively controlled to avoid bus contention.
- All status messages and events are echoed via WebSocket to connected clients.
- The LED strip is refreshed only when a valid command is received.

📅 BUILD INFO:
---------------
- Build Timestamp: Automatically inserted with `_DATE_` and `_TIME_`
- Printed on boot for debugging firmware versions

===============================================================
*/

#include <WiFi.h>
#include <AsyncTCP.h>
#include <ESPAsyncWebServer.h>
#include <Preferences.h>
#include <ESPmDNS.h>
#include <Update.h>
#include <Adafruit_NeoPixel.h>

// === CONFIGURATION ===
#define LED_PIN         5
#define LED_COUNT       900

#define RS485_RX_PIN    16
#define RS485_TX_PIN    17
#define RS485_DIR_PIN   4      // Direction control pin (DE+RE on RS485 chip)

#define BUILD_TIMESTAMP _DATE_ " " _TIME_

const char* ssid = "Gokapture";
const char* password = "P@ssw0rd";

// === OBJECTS ===
Preferences prefs;
AsyncWebServer server(80);
AsyncWebSocket ws("/ws");
Adafruit_NeoPixel strip(LED_COUNT, LED_PIN, NEO_GRB + NEO_KHZ800);
HardwareSerial RS485Serial(2); // UART2

uint8_t slave_id = 0;

// === UTILITIES ===
void notifyClients(const String &msg) {
  ws.textAll(msg + "\n");
}

void logBootInfo() {
  notifyClients("🔌 LED Slave Booted");
  notifyClients("Slave ID: " + String(slave_id));
  notifyClients("IP Address: " + WiFi.localIP().toString());
  notifyClients("Hostname: slave" + String(slave_id) + ".local");
  notifyClients("Firmware Build: " + String(BUILD_TIMESTAMP));
}

// === LED CONTROL ===
void setStripColor(String color) {
  uint32_t c;
  if      (color.equalsIgnoreCase("red"))    c = strip.Color(255, 0, 0);
  else if (color.equalsIgnoreCase("green"))  c = strip.Color(0, 255, 0);
  else if (color.equalsIgnoreCase("blue"))   c = strip.Color(0, 0, 255);
  else if (color.equalsIgnoreCase("white"))  c = strip.Color(255, 255, 255);
  else if (color.equalsIgnoreCase("yellow")) c = strip.Color(255, 255, 0);
  else if (color.equalsIgnoreCase("off"))    c = strip.Color(0, 0, 0);
  else return;

  for (int i = 0; i < strip.numPixels(); i++) {
    strip.setPixelColor(i, c);
  }
  strip.show();
}

// === PARSE & EXECUTE COMMAND ===
void parseCommand(String msg) {
  msg.trim();
  int spaceIndex = msg.indexOf(' ');
  if (spaceIndex == -1) return;

  String idStr = msg.substring(0, spaceIndex);
  String color = msg.substring(spaceIndex + 1);
  idStr.trim();
  color.trim();

  if (idStr.toInt() == slave_id) {
    notifyClients("✅ Accepted Command: " + msg);
    setStripColor(color);
  } else {
    notifyClients("⛔ Ignored Command: " + msg);
  }
}

// === OTA UPDATE PAGE ===
void setupOTA() {
  server.on("/update", HTTP_GET, [](AsyncWebServerRequest *request){
    request->send_P(200, "text/html", R"rawliteral(
      <!DOCTYPE html><html><head><title>OTA Update</title>
      <style>body{font-family:Arial;text-align:center;padding:50px;}input,a{padding:10px 20px;margin:10px;border-radius:5px;background:#4CAF50;color:#fff;text-decoration:none;border:none;}a{background:#2196F3;}</style></head><body>
      <h1>OTA Firmware Update</h1>
      <form method='POST' action='/update' enctype='multipart/form-data'>
        <input type='file' name='update'><br>
        <input type='submit' value='Upload & Update'>
      </form>
      <a href="/">Back to Console</a>
      </body></html>)rawliteral");
  });

  server.on("/update", HTTP_POST,
    [](AsyncWebServerRequest *request){
      if (Update.hasError())
        request->send(500, "text/plain", "❌ Update Failed");
      else
        request->send(200, "text/plain", "✅ Update successful. Rebooting...");
      delay(1000);
      ESP.restart();
    },
    [](AsyncWebServerRequest *request, String filename, size_t index, uint8_t *data, size_t len, bool final){
      if (!index && !Update.begin(UPDATE_SIZE_UNKNOWN)) Update.printError(Serial);
      if (!Update.hasError() && Update.write(data, len) != len) Serial.println("Write failed!");
      if (final && Update.end(true)) Serial.printf("Update Success: %u bytes\n", index + len);
      else if (final) Update.printError(Serial);
    }
  );
}

// === WEB PAGE UI ===
void setupWebPage() {
  server.on("/", HTTP_GET, [](AsyncWebServerRequest *request) {
    String html = R"rawliteral(
      <!DOCTYPE html><html><head><meta charset="utf-8"><title>)rawliteral"
      + String("LED Slave " + String(slave_id)) + R"rawliteral( Console</title>
      <style>body{font-family:Arial;background:#f9f9f9;color:#333;display:flex;flex-direction:column;align-items:center;justify-content:center;height:100vh;margin:0;}#log{background:#eee;border:1px solid #ccc;padding:15px;width:90%;max-height:55vh;overflow-y:auto;border-radius:6px;white-space:pre-wrap;}button,a,input[type="text"]{margin-top:10px;padding:10px 20px;border-radius:5px;font-size:16px;border:none;}button,a{background:#2196F3;color:#fff;cursor:pointer;text-decoration:none;}input[type="text"]{width:60%;border:1px solid #aaa;}</style>
      </head><body><h1>LED Slave Console</h1>
      <div id="log">Booting...\n</div>
      <input type="text" id="msgInput" placeholder="Type message like '1 red'...">
      <button onclick="sendMsg()">Send</button>
      <button onclick="clearLog()">Clear Log</button>
      <a href="/update">OTA Update</a>
      <script>
        const log = document.getElementById("log");
        const ws = new WebSocket("ws://" + location.host + "/ws");
        ws.onmessage = e => { log.textContent += e.data + "\n"; log.scrollTop = log.scrollHeight; };
        function sendMsg() {
          let msg = document.getElementById("msgInput").value;
          if (msg) ws.send(msg);
          document.getElementById("msgInput").value = "";
        }
        function clearLog() { log.textContent = ""; }
      </script></body></html>
    )rawliteral";

    request->send(200, "text/html", html);
  });
}

// === SETUP ===
void setup() {
  Serial.begin(115200);
  Serial.println("Booting...");

  pinMode(RS485_DIR_PIN, OUTPUT);
  digitalWrite(RS485_DIR_PIN, LOW); // Start in receive mode

  strip.begin();
  strip.show();

  prefs.begin("slave", true);
  slave_id = prefs.getUChar("id", 0);
  prefs.end();

  RS485Serial.begin(115200, SERIAL_8N1, RS485_RX_PIN, RS485_TX_PIN);

  delay(2000); // Let RS485 & master settle

  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(300);
  }

  String hostname = "slave" + String(slave_id);
  MDNS.begin(hostname.c_str());

  ws.onEvent([](AsyncWebSocket *server, AsyncWebSocketClient *client,
                AwsEventType type, void *arg, uint8_t *data, size_t len) {
    if (type == WS_EVT_CONNECT) {
      client->text("Connected to LED Slave " + String(slave_id));
      logBootInfo();
    } else if (type == WS_EVT_DATA) {
      AwsFrameInfo *info = (AwsFrameInfo *)arg;
      if (info->final && info->index == 0 && info->len == len && info->opcode == WS_TEXT) {
        String msg = "";
        for (size_t i = 0; i < len; i++) msg += (char)data[i];
        notifyClients("Received (WS): " + msg);
        parseCommand(msg);
      }
    }
  });

  server.addHandler(&ws);
  setupOTA();
  setupWebPage();
  server.begin();

  notifyClients("✅ ESP32 Slave Ready");
}

// === LOOP ===
void loop() {
  static String rs485Buffer = "";

  while (RS485Serial.available()) {
    char c = RS485Serial.read();
    if (c == '\n') {
      rs485Buffer.trim();
      if (rs485Buffer.length() > 0) {
        notifyClients("Received (RS485): " + rs485Buffer);
        parseCommand(rs485Buffer);
      }
      rs485Buffer = "";
    } else {
      rs485Buffer += c;
    }
  }
}